# docker run -it -p 8080:8080 -p 9990:9990 jbossdemocentral/brms-realtime-decicion-server-demo
FROM asaran/brms-realtime-decicion-server-demo
MAINTAINER Anurag Saran asaran@redhat.com
EXPOSE 8080
